name: update resources

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install dart sass
        run: sudo snap install dart-sass --edge
      - name: setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: 0.147.8
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install
        run: |
          npm ci
          npm run prepare
      - name: clean resources
        run: |
          rm -rf resources/* exampleSite/resources/*
      - name: build
        run: npm run build
      - name: commit resources
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: build resources'
          file_pattern: resources/** exampleSite/resources/**
